program: main.py
command: 
  - ${env}
  - venv/Scripts/python.exe
  - ${program}
  - ${args}
method: bayes
project: detect-sleep-states
name: sweep-gru
metric:
  goal: maximize
  name: cv_score
parameters:
  models:
    parameters:
      Sweep-GRU:
        parameters:
          type:
            value: event-res-gru
          loss:
            values:
            - mse-torch
            - shrinkage-loss
            - kldiv-torch
            - mae-torch
          optimizer:
            values:
            - adam-torch
            - adamw-torch
            - sgd-torch
            - adagrad-torch
            - adadelta-torch
            - rmsprop-torch
          epochs:
            value: 100
          batch_size:
            values:
            - 16
            - 32
            - 64
          lr:
            values:
            - 0.0001
            - 0.00025
            - 0.0005
            - 0.00075
            - 0.001
          early_stopping:
            values:
            - 5
            - 8
            - 10
            - 15
            - 20
          activation_delay:
            values:
            - 0
            - 7
            - 15
          network_params:
            parameters:
              hidden_size:
                values:
                - 4
                - 8
                - 16
                - 32
                - 64
              n_layers:
                values:
                - 3
                - 4
                - 5
                - 6
                - 7
              activation:
                values:
                - relu
                - gelu
          lr_schedule:
            parameters:
              t_initial:
                values:
                - 25
                - 50
                - 100
              warmup_t:
                values:
                - 0
                - 5
                - 10
              warmup_lr_init:
                value: 1.0e-06
              lr_min:
                values:
                - 2.0e-08
                - 2.0e-06
                - 0.0002
          threshold:
            value: 0