command:
  - ${env}
  - venv/Scripts/python.exe
  - ${program}
  - ${args}
method: bayes
metric:
  goal: maximize
  name: cv_score
name: sweep-gru-2
parameters:
  models:
    parameters:
      Sweep-GRU:
        parameters:
          activation_delay:
            max: 30
            min: 0
          batch_size:
            max: 256
            min: 16
          early_stopping:
            max: 20
            min: 5
          epochs:
            value: 100
          loss:
            values:
              - mse-torch
              - shrinkage-loss
              - kldiv-torch
              - mae-torch
          lr:
            max: 0.01
            min: 1e-05
          lr_schedule:
            parameters:
              cycle_limit:
                max: 5
                min: 1
              lr_min:
                max: 0.0002
                min: 1e-08
              t_initial:
                max: 50
                min: 20
              warmup_lr_init:
                value: 1e-06
              warmup_t:
                max: 10
                min: 0
          network_params:
            parameters:
              activation:
                values:
                  - relu
                  - gelu
              hidden_size:
                max: 64
                min: 4
              n_layers:
                max: 8
                min: 4
          optimizer:
            values:
              - adam-torch
              - adamw-torch
              - rmsprop-torch
          threshold:
            value: 0
          type:
            value: event-res-gru
program: main.py
project: detect-sleep-states