program: main.py
command: 
  - ${env}
  - venv/Scripts/python.exe
  - ${program}
  - ${args}
method: bayes
project: detect-sleep-states
name: sweep-gru
metric:
  goal: maximize
  name: cv_score
parameters:
  hpo_model:
    parameters:
      name:
        value: gru_sweep
      architecture:
        parameters:
          activation_delay:
            max: 50
            min: 0
          batch_size:
            max: 128
            min: 16
          early_stopping:
            max: 50
            min: 1
          epochs:
            value: 250
          loss:
            values:
              - mse-torch
              - shrinkage-loss
              - kldiv-torch
          lr:
            max: 0.1
            min: 1e-06
          lr_schedule:
            parameters:
              cycle_limit:
                max: 5
                min: 1
              lr_min:
                max: 0.01
                min: 1e-08
              t_initial:
                max: 50
                min: 10
              warmup_lr_init:
                value: 1e-06
              warmup_t:
                max: 10
                min: 0
          mask_unlabeled:
            values:
              - true
              - false
          network_params:
            parameters:
              activation:
                values:
                  - relu
                  - gelu
              hidden_size:
                max: 64
                min: 4
              n_layers:
                max: 10
                min: 4
          optimizer:
            values:
              - adam-torch
              - adamw-torch
          threshold:
            value: 0
          type:
            value: event-res-gru