command:
  - ${env}
  - venv/Scripts/python.exe
  - ${program}
  - ${args}
method: bayes
project: detect-sleep-states
program: main.py
name: sweep-gru-4
metric:
  goal: maximize
  name: cv_score
parameters:
  hpo_model:
    parameters:
      name:
        value: gru_sweep
      data_info:
        parameters:
          downsampling_factor:
            values:
              - 3
              - 4
              - 6
              - 12
              - 24
          latitude:
            value: 40.73061
          longitude:
            value: -73.935242
          window_size:
            value: 17280
      preprocessing:
        value: [
          {
              "kind": "mem_reduce",
              "id_encoding_path": "series_id_encoding.json"
          },
          {
              "kind": "similarity_nan",
              "as_feature": true
          },
          {
              "kind": "add_state_labels",
              "id_encoding_path": "series_id_encoding.json",
              "events_path": "data/raw/train_events.csv",
              "use_similarity_nan": true,
              "fill_limit": 8640,
              "nan_tolerance_window": 5
          },
          {
              "kind": "add_event_labels",
              "id_encoding_path": "series_id_encoding.json",
              "events_path": "data/raw/train_events.csv",
              "smoothing": 0
          },
          {
              "kind": "split_windows"
          }]
      feature_engineering:
        value: [
          {
              "kind": "time",
              "time_features": ["hour","minute"]
          },
          {
              "kind": "sun",
              "sun_features": ["azimuth", "altitude"]
          },
          {
              "kind": "rotation",
              "window_sizes": [12, 36, 60, 120, 240, 360, 1000]
          }]
      pretraining:
        parameters:
          downsample:
            parameters:
              features:
                value: ["f_anglez", "f_enmo"]
              methods:
                value: ["min", "max", "mean", "std", "median", "range", "var"]
              standard:
                value: "mean"
          test_size:
            value: 0.2
          scaler:
            parameters:
              kind:
                value: "standard-scaler"
              copy:
                value: true
      architecture:
        parameters:
          activation_delay:
            max: 50
            min: 0
          batch_size:
            max: 128
            min: 16
          early_stopping:
            max: 50
            min: 1
          epochs:
            value: 5
          loss:
            values:
              - mse-torch
              - shrinkage-loss
              - kldiv-torch
          lr:
            max: 0.1
            min: 1e-06
          lr_schedule:
            parameters:
              cycle_limit:
                max: 4
                min: 1
              lr_min:
                max: 0.01
                min: 1e-08
              t_initial:
                max: 50
                min: 10
              warmup_lr_init:
                value: 1e-06
              warmup_t:
                max: 10
                min: 0
          mask_unlabeled:
            values:
              - true
              - false
          network_params:
            parameters:
              activation:
                values:
                  - relu
                  - gelu
              hidden_size:
                max: 64
                min: 4
              n_layers:
                max: 10
                min: 4
          optimizer:
            values:
              - adam-torch
              - adamw-torch
          threshold:
            value: 0
          type:
            value: event-res-gru
